
package com.viruswar.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ServerServiceService", targetNamespace = "http://communication.server.viruswar.com/", wsdlLocation = "http://localhost:8081/viruswar?wsdl")
public class ServerServiceService
    extends Service
{

    private final static URL SERVERSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException SERVERSERVICESERVICE_EXCEPTION;
    private final static QName SERVERSERVICESERVICE_QNAME = new QName("http://communication.server.viruswar.com/", "ServerServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8081/viruswar?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SERVERSERVICESERVICE_WSDL_LOCATION = url;
        SERVERSERVICESERVICE_EXCEPTION = e;
    }

    public ServerServiceService() {
        super(__getWsdlLocation(), SERVERSERVICESERVICE_QNAME);
    }

    public ServerServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SERVERSERVICESERVICE_QNAME, features);
    }

    public ServerServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVERSERVICESERVICE_QNAME);
    }

    public ServerServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SERVERSERVICESERVICE_QNAME, features);
    }

    public ServerServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServerServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ServerService
     */
    @WebEndpoint(name = "ServerServicePort")
    public ServerService getServerServicePort() {
        return super.getPort(new QName("http://communication.server.viruswar.com/", "ServerServicePort"), ServerService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServerService
     */
    @WebEndpoint(name = "ServerServicePort")
    public ServerService getServerServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://communication.server.viruswar.com/", "ServerServicePort"), ServerService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SERVERSERVICESERVICE_EXCEPTION!= null) {
            throw SERVERSERVICESERVICE_EXCEPTION;
        }
        return SERVERSERVICESERVICE_WSDL_LOCATION;
    }

}
