
package com.viruswar.webservice;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ServerService", targetNamespace = "http://communication.server.viruswar.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ServerService {


    /**
     * 
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "changeMovesPermitFlags", targetNamespace = "http://communication.server.viruswar.com/", className = "com.viruswar.webservice.ChangeMovesPermitFlags")
    @ResponseWrapper(localName = "changeMovesPermitFlagsResponse", targetNamespace = "http://communication.server.viruswar.com/", className = "com.viruswar.webservice.ChangeMovesPermitFlagsResponse")
    @Action(input = "http://communication.server.viruswar.com/ServerService/changeMovesPermitFlagsRequest", output = "http://communication.server.viruswar.com/ServerService/changeMovesPermitFlagsResponse")
    public void changeMovesPermitFlags(
        @WebParam(name = "arg0", targetNamespace = "")
        boolean arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        boolean arg1);

    /**
     * 
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "checkGameEnded", targetNamespace = "http://communication.server.viruswar.com/", className = "com.viruswar.webservice.CheckGameEnded")
    @ResponseWrapper(localName = "checkGameEndedResponse", targetNamespace = "http://communication.server.viruswar.com/", className = "com.viruswar.webservice.CheckGameEndedResponse")
    @Action(input = "http://communication.server.viruswar.com/ServerService/checkGameEndedRequest", output = "http://communication.server.viruswar.com/ServerService/checkGameEndedResponse")
    public boolean checkGameEnded();

    /**
     * 
     * @return
     *     returns com.viruswar.webservice.ServerResponseDto
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "handleCrossMoves", targetNamespace = "http://communication.server.viruswar.com/", className = "com.viruswar.webservice.HandleCrossMoves")
    @ResponseWrapper(localName = "handleCrossMovesResponse", targetNamespace = "http://communication.server.viruswar.com/", className = "com.viruswar.webservice.HandleCrossMovesResponse")
    @Action(input = "http://communication.server.viruswar.com/ServerService/handleCrossMovesRequest", output = "http://communication.server.viruswar.com/ServerService/handleCrossMovesResponse")
    public ServerResponseDto handleCrossMoves();

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "isMovePermit", targetNamespace = "http://communication.server.viruswar.com/", className = "com.viruswar.webservice.IsMovePermit")
    @ResponseWrapper(localName = "isMovePermitResponse", targetNamespace = "http://communication.server.viruswar.com/", className = "com.viruswar.webservice.IsMovePermitResponse")
    @Action(input = "http://communication.server.viruswar.com/ServerService/isMovePermitRequest", output = "http://communication.server.viruswar.com/ServerService/isMovePermitResponse")
    public boolean isMovePermit(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findWhoseTurn", targetNamespace = "http://communication.server.viruswar.com/", className = "com.viruswar.webservice.FindWhoseTurn")
    @ResponseWrapper(localName = "findWhoseTurnResponse", targetNamespace = "http://communication.server.viruswar.com/", className = "com.viruswar.webservice.FindWhoseTurnResponse")
    @Action(input = "http://communication.server.viruswar.com/ServerService/findWhoseTurnRequest", output = "http://communication.server.viruswar.com/ServerService/findWhoseTurnResponse")
    public String findWhoseTurn();

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getClientGroup", targetNamespace = "http://communication.server.viruswar.com/", className = "com.viruswar.webservice.GetClientGroup")
    @ResponseWrapper(localName = "getClientGroupResponse", targetNamespace = "http://communication.server.viruswar.com/", className = "com.viruswar.webservice.GetClientGroupResponse")
    @Action(input = "http://communication.server.viruswar.com/ServerService/getClientGroupRequest", output = "http://communication.server.viruswar.com/ServerService/getClientGroupResponse")
    public String getClientGroup();

    /**
     * 
     * @return
     *     returns java.util.List<com.viruswar.webservice.MadeCommandsDto>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getMadeGameMoves", targetNamespace = "http://communication.server.viruswar.com/", className = "com.viruswar.webservice.GetMadeGameMoves")
    @ResponseWrapper(localName = "getMadeGameMovesResponse", targetNamespace = "http://communication.server.viruswar.com/", className = "com.viruswar.webservice.GetMadeGameMovesResponse")
    @Action(input = "http://communication.server.viruswar.com/ServerService/getMadeGameMovesRequest", output = "http://communication.server.viruswar.com/ServerService/getMadeGameMovesResponse")
    public List<MadeCommandsDto> getMadeGameMoves();

    /**
     * 
     * @param arg0
     * @return
     *     returns com.viruswar.webservice.ServerResponseDto
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "handleMoves", targetNamespace = "http://communication.server.viruswar.com/", className = "com.viruswar.webservice.HandleMoves")
    @ResponseWrapper(localName = "handleMovesResponse", targetNamespace = "http://communication.server.viruswar.com/", className = "com.viruswar.webservice.HandleMovesResponse")
    @Action(input = "http://communication.server.viruswar.com/ServerService/handleMovesRequest", output = "http://communication.server.viruswar.com/ServerService/handleMovesResponse")
    public ServerResponseDto handleMoves(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
